//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DISERTATIE_5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACC_SUBS_INT
    {
        public long ACC_SUBS_INT_ID { get; set; }
        public long ACCOUNT_ID { get; set; }
        public long SUBSCRIBER_ID { get; set; }
        public long SUBSCRIBER_TYPE_ID { get; set; }
        public Nullable<short> MAIN { get; set; }
        public Nullable<decimal> BATCH_NUMBER { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public string LAST_UPDATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
    
        public virtual ACCOUNTS ACCOUNTS { get; set; }
        public virtual SUBSCRIBER_TYPES SUBSCRIBER_TYPES { get; set; }
        public virtual SUBSCRIBERS SUBSCRIBERS { get; set; }
    }
}
