//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DISERTATIE_5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANK_ACCOUNTS
    {
        public BANK_ACCOUNTS()
        {
            this.CLIENTS = new HashSet<CLIENTS>();
        }
    
        public long BANK_ACCOUNT_ID { get; set; }
        public string ACCOUNT { get; set; }
        public string BANK_NAME { get; set; }
        public string BANK_CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public string LAST_UPDATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
        public string CURRENCY { get; set; }
    
        public virtual ICollection<CLIENTS> CLIENTS { get; set; }
    }
}
