//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DISERTATIE_5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CASE_DETAILS_V
    {
        public long CASE_ID { get; set; }
        public string ZONE { get; set; }
        public string CLIENT_NAME { get; set; }
        public Nullable<decimal> BALANCE { get; set; }
        public string PA_STATUS { get; set; }
        public Nullable<decimal> PA_MADE { get; set; }
        public Nullable<decimal> PA_BROKEN { get; set; }
        public Nullable<decimal> PA_KEPT { get; set; }
        public Nullable<decimal> PA_CANCELLED { get; set; }
    }
}
