//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DISERTATIE_5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CASES_SEARCH
    {
        public Nullable<decimal> UNIQUE_ID { get; set; }
        public Nullable<long> CLIENT_ID { get; set; }
        public string ZONE { get; set; }
        public string OWNER { get; set; }
        public Nullable<long> CASE_ID { get; set; }
        public long ACCOUNT_ID { get; set; }
        public string CUSTOMER_ID { get; set; }
        public string SSN { get; set; }
        public string NAME { get; set; }
        public string SUBSCRIBER_TYPE { get; set; }
        public string CONTRACT_NUMBER { get; set; }
    }
}
