//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DISERTATIE_5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEC_USERS
    {
        public decimal SEC_USER_ID { get; set; }
        public string USERNAME { get; set; }
        public string FULL_NAME { get; set; }
        public string SEC_PASSWORD { get; set; }
        public Nullable<decimal> ACTIVE { get; set; }
        public Nullable<decimal> ISADMIN { get; set; }
        public Nullable<System.DateTime> START_ACTIVE_DATE { get; set; }
        public Nullable<System.DateTime> END_ACTIVE_DATE { get; set; }
        public Nullable<System.DateTime> PASSWORD_EXPIRATION_DATE { get; set; }
        public Nullable<decimal> BLOCKED { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public string LAST_UPDATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
        public Nullable<decimal> FAILED_ATTEMPTS { get; set; }
    }
}
