//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DISERTATIE_5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBSCRIBER_ADDRESSES
    {
        public long SUBSCRIBER_ADDRESS_ID { get; set; }
        public long ADDRESS_TYPE_ID { get; set; }
        public long SUBSCRIBER_ID { get; set; }
        public Nullable<short> MAIN_ADDRESS { get; set; }
        public string STREET { get; set; }
        public string STREET_NUMBER { get; set; }
        public string BUILDING { get; set; }
        public string STAIR { get; set; }
        public string FLOOR { get; set; }
        public string APARTMENT { get; set; }
        public string CITY { get; set; }
        public string DISTRICT { get; set; }
        public string COUNTRY { get; set; }
        public Nullable<decimal> BATCH_NUMBER { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public string LAST_UPDATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
        public Nullable<long> SOURCE { get; set; }
        public string COMMENTS { get; set; }
    
        public virtual ADDRESS_TYPES ADDRESS_TYPES { get; set; }
        public virtual SOURCE_TYPES SOURCE_TYPES { get; set; }
        public virtual SUBSCRIBERS SUBSCRIBERS { get; set; }
    }
}
