//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DISERTATIE_5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBSCRIBER_DATA_V
    {
        public Nullable<long> CASE_ID { get; set; }
        public long SUBSCRIBER_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string SUBSCRIBER_TYPE { get; set; }
        public Nullable<short> MAIN { get; set; }
        public string SSN { get; set; }
    }
}
