//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DISERTATIE_5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBSCRIBER_ADDRESSES_V
    {
        public long SUBSCRIBER_ID { get; set; }
        public string ADDRESS_TYPE { get; set; }
        public Nullable<short> MAIN_ADDRESS { get; set; }
        public string STREET { get; set; }
        public string STREET_NUMBER { get; set; }
        public string BUILDING { get; set; }
        public string STAIR { get; set; }
        public string FLOOR { get; set; }
        public string APARTMENT { get; set; }
        public string CITY { get; set; }
        public string DISTRICT { get; set; }
        public string COUNTRY { get; set; }
        public string SOURCE_TYPE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
    }
}
