//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DISERTATIE_5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZONE_TYPES
    {
        public ZONE_TYPES()
        {
            this.ACCOUNTS = new HashSet<ACCOUNTS>();
            this.CASES = new HashSet<CASES>();
        }
    
        public string ZONE_ID { get; set; }
        public string NAME { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public string LAST_UPDATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE_DATE { get; set; }
    
        public virtual ICollection<ACCOUNTS> ACCOUNTS { get; set; }
        public virtual ICollection<CASES> CASES { get; set; }
    }
}
